export const ActionTypes = {
  ADD_CARDS: "ADD_CARDS",
  SHOW_CARDS_NUMBER: "SHOW_CARDS_NUMBER",
  LOCK: "LOCK",
  ADD_TO_GP: "ADD_TO_GP",
  ARCHIVE_CARDS:"ARCHIVE_CARDS",
  SET_AS_DEFAULT:"SET_AS_DEFAULT"
};